# Generated by Django 6.0.6 on 2026-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=150, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Copy or preview of the certificate', null=True, upload_to='certificates/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current role', null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Current Role?')),
                ('order', models.IntegerField(default=0, help_text='Display order (usually higher number is older)')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Full Stack Developer & Designer', max_length=200)),
                ('bio', models.TextField(help_text='Short introductory bio')),
                ('about_me', models.TextField(help_text='Detailed personal description for About section')),
                ('profile_image', models.ImageField(help_text='Main profile picture', upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, help_text='X / Twitter URL', null=True)),
                ('resume', models.FileField(blank=True, help_text='Upload CV/Resume PDF', null=True, upload_to='resumes/')),
                ('logo_text', models.CharField(default='Portfolio', help_text='Logo text displayed in navbar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description of the project')),
                ('detail_description', models.TextField(blank=True, help_text='Detailed project breakdown/features (optional)', null=True)),
                ('image', models.ImageField(help_text='Project preview screenshot', upload_to='projects/')),
                ('category', models.CharField(help_text='e.g. Web App, Mobile, Game, UI/UX', max_length=100)),
                ('technologies', models.CharField(help_text='Comma-separated technologies (e.g. Django, React, Bootstrap 5)', max_length=250)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Display first or highlight on the home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Bootstrap icon class name, e.g. bi-code-slash, bi-laptop, bi-palette', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=80, help_text='Skill level percentage (0 to 100)')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Tools', 'Tools & Devops'), ('Other', 'Other/Soft Skills')], default='Frontend', max_length=50)),
            ],
            options={
                'ordering': ['category', '-percentage'],
            },
        ),
    ]
